enum ShopActionType {
  GET_SHOP_DETAIL = 'GET_SHOP_DETAIL',
  GET_SHOP_DETAIL_SUCCESS = 'GET_SHOP_DETAIL_SUCCESS',
  GET_SHOP_DETAIL_FAILED = 'GET_SHOP_DETAIL_FAILED',
}

export default ShopActionType;
